INSERT OR IGNORE INTO forms(id, name, active_version) VALUES
  ('form_road_test', 'Road test package', 1),
  ('form_rental', 'Car rental', 1),
  ('form_lesson', 'Driving lesson', 1);

INSERT OR IGNORE INTO form_versions(id, form_id, version, schema_json) VALUES
  ('fv_road_1', 'form_road_test', 1, '{"id":"form_road_test","name":"Road test package","version":1,"fields":[{"id":"name","key":"fullName","type":"text","label":{"en":"Full name","fr":"Nom complet"},"required":true,"calendarVisible":true,"adminListVisible":true,"retentionCategory":"contact"},{"id":"email","key":"email","type":"email","label":{"en":"Email address","fr":"Adresse courriel"},"required":true,"calendarVisible":true,"adminListVisible":true,"retentionCategory":"contact"},{"id":"phone","key":"phone","type":"phone","label":{"en":"Phone number","fr":"Numéro de téléphone"},"required":true,"calendarVisible":true,"adminListVisible":true,"retentionCategory":"contact"},{"id":"exam","key":"examDateTime","type":"datetime","label":{"en":"Official SAAQ exam date and time","fr":"Date et heure de l’examen SAAQ"},"required":true,"calendarVisible":true,"adminListVisible":true,"retentionCategory":"operational"},{"id":"class","key":"licenseClass","type":"select","label":{"en":"Licence class","fr":"Classe de permis"},"required":true,"options":[{"value":"5","label":{"en":"Class 5 — Passenger vehicle","fr":"Classe 5 — Véhicule de promenade"}}],"retentionCategory":"operational"},{"id":"notes","key":"notes","type":"textarea","label":{"en":"Anything we should know?","fr":"Quelque chose à nous signaler?"},"required":false,"calendarVisible":true,"retentionCategory":"operational"}]}');

INSERT OR IGNORE INTO form_versions(id, form_id, version, schema_json) VALUES
  ('fv_rental_1', 'form_rental', 1, '{"id":"form_rental","name":"Car rental","version":1,"fields":[{"id":"name","key":"fullName","type":"text","label":{"en":"Full name","fr":"Nom complet"},"required":true,"calendarVisible":true,"adminListVisible":true,"retentionCategory":"contact"},{"id":"email","key":"email","type":"email","label":{"en":"Email address","fr":"Adresse courriel"},"required":true,"calendarVisible":true,"adminListVisible":true,"retentionCategory":"contact"},{"id":"phone","key":"phone","type":"phone","label":{"en":"Phone number","fr":"Numéro de téléphone"},"required":true,"calendarVisible":true,"adminListVisible":true,"retentionCategory":"contact"},{"id":"exam","key":"examDateTime","type":"datetime","label":{"en":"Official SAAQ exam date and time","fr":"Date et heure de l’examen SAAQ"},"required":true,"calendarVisible":true,"adminListVisible":true,"retentionCategory":"operational"},{"id":"consent","key":"consent","type":"consent","label":{"en":"I confirm my SAAQ appointment is booked.","fr":"Je confirme que mon rendez-vous SAAQ est réservé."},"required":true,"retentionCategory":"consent"}]}');

INSERT OR IGNORE INTO form_versions(id, form_id, version, schema_json) VALUES
  ('fv_lesson_1', 'form_lesson', 1, '{"id":"form_lesson","name":"Driving lesson","version":1,"fields":[{"id":"name","key":"fullName","type":"text","label":{"en":"Full name","fr":"Nom complet"},"required":true,"calendarVisible":true,"adminListVisible":true,"retentionCategory":"contact"},{"id":"email","key":"email","type":"email","label":{"en":"Email address","fr":"Adresse courriel"},"required":true,"calendarVisible":true,"adminListVisible":true,"retentionCategory":"contact"},{"id":"phone","key":"phone","type":"phone","label":{"en":"Phone number","fr":"Numéro de téléphone"},"required":true,"calendarVisible":true,"adminListVisible":true,"retentionCategory":"contact"},{"id":"experience","key":"experience","type":"radio","label":{"en":"Driving experience","fr":"Expérience de conduite"},"required":true,"options":[{"value":"new","label":{"en":"I’m just starting","fr":"Je débute"}},{"value":"some","label":{"en":"Some practice","fr":"Un peu de pratique"}},{"value":"test","label":{"en":"Preparing for my test","fr":"Je prépare mon examen"}}],"retentionCategory":"operational"},{"id":"area","key":"meetingArea","type":"text","label":{"en":"Preferred meeting area","fr":"Lieu de rencontre souhaité"},"required":false,"calendarVisible":true,"retentionCategory":"operational"}]}');
